device_id: "rpi-007"  # Identifiant unique du Pi (doit être enregistré côté serveur)

ws_url: "ws://192.168.0.118:3002"  # Adresse du serveur WebSocket

sensor_ids:
  temperature: "685b4588a3ef651df62f192b"
  humidity: "685b47e1a3ef651df62f194d"
  led: "685b4590a3ef651df62f1939"  

gpio:
  temp_pin: 4               # DHT11 (GPIO 4)
  button_pin: 13            # Bouton en pull-down
  led_humidity_pin: 12      # LED pour signaler humidité > seuil
  led_control_pin: 25       # LED à contrôler à distance via WebSocket

thresholds:
  humidity: 50              # Seuil d’alerte pour l’humidité
